language: node_js
node_js:
  - "4.2"

branches:
  only:
    - master

script:
  - gulp ngTemplates test --prod
  
after_script:
  - npm run coveralls

notifications:
  email:
    recipients:
      - chrisleedavis@gmail.com
